package cn.com.omnimind.bot.ui.chat

/**
 * Kotlin port of `ui/lib/l10n/legacy_text_localizer.dart`.
 *
 * Rewrites the legacy Chinese UI strings to English. Unlike the Dart class it
 * holds no locale state: callers pass [english] explicitly. The exact map is
 * generated mechanically from the Dart source (423 entries); the regex
 * rewriters keep the Dart order.
 *
 * Regex note: Dart `RegExp` follows JavaScript semantics, so `.` excludes
 * line terminators, `\s` is the Unicode whitespace set and a non-multiline
 * `$` matches only at the very end of input. The patterns below spell those
 * out explicitly ([JS_DOT], [JS_WS], `\z`).
 */
internal object LegacyTextLocalizer {
    fun localize(text: String, english: Boolean): String {
        if (!english) {
            return text
        }
        val exact = exactEn[text]
        if (exact != null) {
            return exact
        }
        for ((pattern, rewrite) in regexEn) {
            val match = pattern.find(text)
            if (match != null) {
                return rewrite(match)
            }
        }
        return text
    }

    private const val JS_DOT = "[^\\n\\r\\u2028\\u2029]"
    private const val JS_WS =
        "[\\t\\n\\u000B\\f\\r \\u00A0\\u1680\\u2000-\\u200A\\u2028\\u2029\\u202F\\u205F\\u3000\\uFEFF]"

    /** Translates a Dart regex body: `.` → [JS_DOT], `\s` → [JS_WS], `$` → `\z`. */
    private fun js(pattern: String): Regex {
        val out = StringBuilder()
        var index = 0
        while (index < pattern.length) {
            val char = pattern[index]
            when {
                char == '\\' && index + 1 < pattern.length -> {
                    val next = pattern[index + 1]
                    if (next == 's') out.append(JS_WS) else out.append(char).append(next)
                    index += 2
                    continue
                }
                char == '.' -> out.append(JS_DOT)
                char == '$' -> out.append("\\z")
                else -> out.append(char)
            }
            index += 1
        }
        return Regex(out.toString())
    }

    private fun MatchResult.g(index: Int): String = groupValues[index]

    private val regexEn: List<Pair<Regex, (MatchResult) -> String>> = listOf(
        js("^MCP 已开启：(.+)$") to { m -> "MCP enabled: ${m.g(1)}" },
        js("^会话 (\\d+) · 任务 (\\d+)$") to { m -> "Sessions ${m.g(1)} · Tasks ${m.g(2)}" },
        js("^已连接 · (.+)$") to { m -> "Connected · ${m.g(1)}" },
        js("^选择图片失败：(.+)$") to { m -> "Failed to pick image: ${m.g(1)}" },
        js("^自动保存失败：(.+)$") to { m -> "Auto-save failed: ${m.g(1)}" },
        js("^已拉取 (\\d+) 个模型$") to { m -> "Fetched ${m.g(1)} models" },
        js("^暂时无法生成回复，请重试。(.*)$") to { m ->
            val extra = m.g(1).trim()
            if (extra.isEmpty()) {
                "I can't generate a reply right now. Please try again."
            } else {
                "I can't generate a reply right now. Please try again. $extra"
            }
        },
        js("^执行任务前，请先开启：(.+)$") to { m ->
            "Enable these permissions before running tasks: ${m.g(1)}"
        },
        js("^执行任务前需要先开启权限$") to { _ -> "Permissions must be enabled before running tasks" },
        js("^用户: (.+)\\n$") to { m -> "User: ${m.g(1)}\n" },
        js("^继续任务仅要求：(.+)$") to { m -> "Continue requires only: ${m.g(1)}" },
        js("^默认：(.+)$") to { m -> "Default: ${m.g(1)}" },
        js("^恢复默认（(.+)）$") to { m -> "Restore default (${m.g(1)})" },
        js("^(.+) 已清除绑定$") to { m -> "${m.g(1)} binding cleared" },
        js("^(.+) 已恢复默认模型$") to { m -> "${m.g(1)} restored to default model" },
        js("^已切换到 (.+)$") to { m -> "Switched to ${m.g(1)}" },
        js("^已设置思考强度为 (.+)$") to { m -> "Reasoning effort set to ${m.g(1)}" },
        js("^Agent 模型已切换到 (.+)$") to { m -> "Agent model switched to ${m.g(1)}" },
        js("^更新 Agent 模型失败：(.+)$") to { m -> "Failed to update Agent model: ${m.g(1)}" },
        js("^(.+)已复制$") to { m -> "${m.g(1)} copied" },
        js("^(\\d+) 条消息$") to { m -> "${m.g(1)} messages" },
        js("^(.+) · (\\d+) 条消息$") to { m -> "${m.g(1)} · ${m.g(2)} messages" },
        js("^匹配 (\\d+)%$") to { m -> "Match ${m.g(1)}%" },
        js("^(\\d+) 分钟前$") to { m -> "${m.g(1)} min ago" },
        js("^(\\d+) 小时前$") to { m -> "${m.g(1)} hr ago" },
        js("^(\\d+) 天前$") to { m -> "${m.g(1)} days ago" },
        js("^(\\d+) 秒$") to { m -> "${m.g(1)}s" },
        js("^(\\d+) 分 (\\d+) 秒$") to { m -> "${m.g(1)}m ${m.g(2)}s" },
        js("^(\\d+) 次对话 · (\\d+)\\/(\\d+)$") to { m ->
            "${m.g(1)} conversations · ${m.g(2)}/${m.g(3)}"
        },
        js("^无对话 · (\\d+)\\/(\\d+)$") to { m -> "No conversations · ${m.g(1)}/${m.g(2)}" },
        js("^本地 (.+)%$") to { m -> "Local ${m.g(1)}%" },
        js("^云端 (.+)%$") to { m -> "Cloud ${m.g(1)}%" },
        js("^本地 (.+) · 云端 (.+)$") to { m -> "Local ${m.g(1)} · Cloud ${m.g(2)}" },
        js("^正在搜索\\s*(.+?)\\s*技能$") to { m -> "Searching ${m.g(1)} skill" },
        js("^打开\\s*(.+?)\\s*应用$") to { m -> "Opening ${m.g(1)} app" },
        js("^正在打开(.+)$") to { m -> "Opening ${m.g(1)}" },
    )

    /** Number of exact entries; must equal the Dart `_exactEn` literal (423). */
    internal val exactEntryCount: Int get() = exactEn.size

    private val exactEn: Map<String, String> = hashMapOf(
        "宠物" to "Pet",
        "小万" to "OmniAi",
        "小万（OmniAi）" to "OmniAi",
        "默认的桌面悬浮窗宠物" to "Default desktop floating pet",
        "自定义宠物" to "Custom Pet",
        "已选" to "Selected",
        "选择" to "Select",
        "刷新" to "Refresh",
        "唤起宠物" to "Show Pet",
        "收起宠物" to "Hide Pet",
        "宠物列表已刷新" to "Pet list refreshed",
        "选择宠物失败" to "Failed to select pet",
        "导入 Codex 宠物包" to "Import Codex Pet Package",
        "支持 .codex-pet.zip（pet.json + spritesheet.webp）" to "Supports .codex-pet.zip (pet.json + spritesheet.webp)",
        "上传压缩包" to "Upload Package",
        "宠物已导入并选中" to "Pet imported and selected",
        "导入宠物失败" to "Failed to import pet",
        "Codex 动态宠物 · 7 类动作" to "Codex animated pet · 7 action types",
        "收起宠物失败" to "Failed to hide pet",
        "唤起宠物失败，请确认悬浮窗权限已开启" to "Failed to show pet. Please make sure overlay permission is enabled",
        "设置" to "Settings",
        "外观设置" to "Appearance",
        "主题模式" to "Theme Mode",
        "本机服务" to "Local Service",
        "地址" to "Address",
        "Token" to "Token",
        "防止任务运行时屏幕休眠" to "Prevent Screen Sleep During Tasks",
        "任务运行期间保持屏幕常亮，适用于小万（OmniAi）、Agent 和纯聊天" to "Keep the screen awake while OmniAi, Agent, or chat tasks run",
        "任务完成通知" to "Task Completion Notifications",
        "小万（OmniAi）、Agent 和纯聊天完成后推送提醒" to "Notify when OmniAi, Agent, or chat responses finish",
        "需要开启通知权限" to "Notification permission is required",
        "未生成" to "Not generated",
        "复制地址" to "Copy Address",
        "复制 Token" to "Copy Token",
        "刷新 Token" to "Refresh Token",
        "加载中..." to "Loading...",
        "模型与记忆" to "Models & Memory",
        "服务与环境" to "Services & Environment",
        "体验与外观" to "Experience & Appearance",
        "权限与信息" to "Permissions & Info",
        "模型提供商" to "Model Providers",
        "场景模型配置" to "Scene Model Config",
        "Workspace 记忆配置" to "Workspace Memory",
        "MCP 工具" to "MCP Tools",
        "Alpine 环境" to "Terminal Environment",
        "终端环境" to "Terminal Environment",
        "本地 Alpine 与远程 PC Bridge" to "Local terminal environment and remote PC Bridge",
        "本地终端环境与远程 PC Bridge" to "Local terminal environment and remote PC Bridge",
        "Agent 模式" to "Agent Mode",
        "管理 ACP Agent、可用状态与统一模型绑定" to "Manage ACP Agents, availability, and unified model bindings",
        "远程 PC Bridge" to "Remote PC Bridge",
        "仅配置远程 ACP 连接" to "Configure only the remote ACP connection",
        "清除失败" to "Failed to clear",
        "隐藏" to "Hide",
        "显示" to "Show",
        "高级设置" to "Advanced Settings",
        "微信" to "WeChat",
        "会话" to "Sessions",
        "未启用" to "Not enabled",
        "已连接" to "Connected",
        "连接中" to "Connecting",
        "未连接" to "Disconnected",
        "已复制" to "Copied",
        "后台隐藏" to "Hide from Recents",
        "闹钟设置" to "Alarm Settings",
        "振动反馈" to "Vibration Feedback",
        "杂项" to "Misc",
        "首页设置" to "Home Settings",
        "启动时" to "On Startup",
        "恢复上次关闭对话" to "Resume Last Chat",
        "新对话" to "New Chat",
        "选择应用启动后打开的对话" to "Choose which chat opens when the app starts",
        "首页问候" to "Home Greeting",
        "显示问候语" to "Show Greeting",
        "管理聊天首页问候语和快捷指令" to "Manage the chat home greeting and quick prompts",
        "关闭后，聊天首页不再显示问候语和快捷指令" to "When disabled, the chat home will hide the greeting and quick prompts",
        "快捷指令" to "Quick Prompts",
        "新增快捷指令" to "Add Quick Prompt",
        "编辑快捷指令" to "Edit Quick Prompt",
        "删除快捷指令" to "Delete Quick Prompt",
        "删除后该快捷指令将不再显示在首页问候语下方。" to "This quick prompt will no longer appear under the home greeting.",
        "暂无快捷指令" to "No quick prompts",
        "指令名称" to "Prompt Name",
        "填充文本" to "Text to Fill",
        "请填写完整信息" to "Please fill in all fields",
        "固定" to "Pinned",
        "固定到首页" to "Pin to Home",
        "取消固定" to "Unpin",
        "最多固定两个快捷指令" to "Pin up to two quick prompts",
        "首页、后台隐藏、闹钟、振动与打开方式" to "Home, Hide from Recents, alarms, vibration, and open behavior",
        "后台隐藏、闹钟、振动与打开方式" to "Hide from Recents, alarms, vibration, and open behavior",
        "使用小万打开" to "Open with Omnibot",
        "使用小万打开 - 图片" to "Open with Omnibot - Images",
        "使用小万打开 - 文件" to "Open with Omnibot - Files",
        "分别设置图片和文件的打开方式" to "Configure image and file open behavior separately",
        "图片" to "Images",
        "文件" to "Files",
        "复制到 workspace 并在提示词中发送文件路径" to "Copy to workspace and send file paths in the prompt",
        "添加到 workspace，附加到对话，并在提示词中发送文件路径" to "Add to workspace, attach to chat, and send the file path in the prompt",
        "存入 workspace 并发送路径" to "Save to workspace and send path",
        "图片填入对话，其他文件走文件传输" to "Attach images to chat; send other files through file transfer",
        "附加到对话输入框" to "Attach to chat input",
        "照片等文件会直接附加到对话输入框" to "Photos and similar files are attached directly to the chat input",
        "启动文件服务器生成局域网链接" to "Start file server and create a LAN link",
        "生成局域网文件链接" to "Create a LAN file link",
        "非照片文件会启动文件服务器并生成局域网链接" to "Non-photo files start the file server and create a LAN link",
        "默认" to "Default",
        "关于小万" to "About Omnibot",
        "背景来源" to "Background Source",
        "效果预览" to "Preview",
        "效果调整" to "Adjustments",
        "聊天" to "Chat",
        "工作区" to "Workspace",
        "启用背景图" to "Enable background image",
        "本地图片" to "Local Image",
        "图片直链" to "Image URL",
        "选择图片" to "Choose Image",
        "重新选择" to "Choose Again",
        "背景柔化" to "Background Blur",
        "蒙版强度" to "Overlay Strength",
        "蒙版明暗" to "Overlay Brightness",
        "聊天文本大小" to "Chat Text Size",
        "聊天文本颜色" to "Chat Text Color",
        "自动" to "Auto",
        "手动" to "Manual",
        "自定义色号" to "Custom Color",
        "关闭浏览器窗口" to "Close browser window",
        "当前平台暂不支持浏览器工具视图" to "Browser tool view is not supported on this platform yet",
        "悬浮窗权限" to "Overlay",
        "应用列表读取权限" to "Installed Apps Access",
        "Shizuku 权限" to "Shizuku Permission",
        "公共文件访问" to "Public Storage Access",
        "正在调用工具" to "Calling tool",
        "暂时无法生成回复，请重试。" to "I can't generate a reply right now. Please try again.",
        "[只显示最近的部分终端输出]\n" to "[Only the most recent terminal output is shown]\n",
        "搜索全部对话" to "Search",
        "清空搜索" to "Clear search",
        "抱歉，刚刚网络开小差了。再发一次试试？" to "Sorry, the network stumbled just now. Please try sending it again.",
        "小万忙不过来了，等会儿再试试吧" to "Omnibot is busy right now. Please try again in a moment.",
        "设置后台隐藏失败" to "Failed to update hide-from-recents",
        "设置失败" to "Failed to save settings",
        "MCP 已关闭" to "MCP disabled",
        "MCP 开关失败" to "Failed to toggle MCP",
        "已复制访问地址" to "Address copied",
        "已复制 Token" to "Token copied",
        "已刷新 Token" to "Token refreshed",
        "刷新 Token 失败" to "Failed to refresh token",
        "请求应用列表权限失败" to "Failed to request installed apps permission",
        "请输入有效的 http(s) 图片直链" to "Enter a valid http(s) image URL",
        "请输入 #RRGGBB 或 #AARRGGBB" to "Enter #RRGGBB or #AARRGGBB",
        "色号格式不正确" to "Invalid color code",
        "请先选择本地图片" to "Select a local image first",
        "本地图片不存在，请重新选择" to "The local image no longer exists. Please choose it again",
        "尚未选择本地图片" to "No local image selected yet",
        "正在自动保存…" to "Saving changes…",
        "更改会自动保存" to "Changes are saved automatically",
        "正在调用内嵌 Alpine 终端执行命令" to "Running a command in the embedded terminal environment",
        "正在执行内嵌 Alpine 终端命令" to "Executing a command in the embedded terminal environment",
        "终端输出更新中" to "Updating terminal output",
        "🎉Hi，我是小万，我会做很多事，让我展示给你下！" to "🎉Hi, I'm Omnibot. I can do many things, let me show you!",
        "Hi，我是小万" to "Hi, I'm Omnibot",
        "你的 AI 助手，随时准备就绪" to "Your AI assistant, always ready",
        "换一换" to "Shuffle",
        "小万正在思考..." to "Omnibot is thinking...",
        "总结中" to "Summarizing",
        "总结如下" to "Summary",
        "全选" to "Select all",
        "复制" to "Copy",
        "取消" to "Cancel",
        "确认" to "Confirm",
        "确定" to "OK",
        "请稍候..." to "Please wait...",
        "保存并发送" to "Save & Send",
        "未设置模型" to "No model set",
        "发现新版本" to "New version available",
        "打开终端" to "Open terminal",
        "管理终端环境变量" to "Manage terminal environment variables",
        "打开当前会话浏览器" to "Open browser for current session",
        "当前会话还没有可用的浏览器会话" to "No browser session available",
        "纯聊天" to "Chat Only",
        "普通" to "Normal",
        "今天" to "Today",
        "昨天" to "Yesterday",
        "执行中" to "Executing",
        "准备中" to "Pending",
        "执行成功" to "Succeeded",
        "执行失败" to "Failed",
        "已取消" to "Cancelled",
        "等待执行" to "Pending",
        "已暂停" to "Paused",
        "系统" to "System",
        "总结" to "Summary",
        "未知" to "Unknown",
        "识图" to "Image Recognition",
        "未知类型" to "Unknown type",
        "正在回复..." to "Replying...",
        "永不" to "Never",
        "每日" to "Daily",
        "每周" to "Weekly",
        "每月" to "Monthly",
        "每年" to "Yearly",
        "时间" to "Time",
        "日期" to "Date",
        "重复" to "Repeat",
        "任务选项" to "Task options",
        "请选择一个任务" to "Please select a task",
        "请选择你想执行的任务" to "Please select a task to execute",
        "请选择一个应用程序" to "Please select an application",
        "未设置" to "Not set",
        "已过期" to "Expired",
        "即将执行" to "Starting soon",
        "执行" to "Execute",
        "任务" to "Task",
        "好，我来帮你完成" to "OK, I'll help you complete it",
        "用户操作" to "User action",
        "短期记忆" to "Short-term Memory",
        "长期记忆" to "Long-term Memory",
        "删除" to "Delete",
        "已删除" to "Deleted",
        "全部" to "All",
        "删除成功" to "Deleted",
        "删除失败" to "Failed to delete",
        "修改失败" to "Modify failed",
        "修改成功" to "Modified successfully",
        "桌面" to "Desktop",
        "内存中" to "Local Memory",
        "云内存中" to "Cloud Memory",
        "记忆中心" to "Memory Center",
        "技能仓库" to "Skill Store",
        "轨迹" to "Trajectory",
        "聊天记录" to "Chat History",
        "已归档" to "Archived",
        "归档对话" to "Archived Conversations",
        "新增" to "Add",
        "安装" to "Install",
        "未安装" to "Not installed",
        "已安装" to "Installed",
        "已禁用" to "Disabled",
        "启用中" to "Enabled",
        "内置" to "Built-in",
        "用户" to "User",
        "保存成功" to "Saved successfully",
        "记忆" to "Memory",
        "记忆能力" to "Memory Capability",
        "文档内容" to "Document Content",
        "权限说明" to "Permission Notes",
        "授权应用" to "Authorized Apps",
        "编辑" to "Edit",
        "编辑你的消息" to "Edit your message",
        "创建" to "Create",
        "任务名称" to "Task Name",
        "启动命令" to "Start Command",
        "工作目录" to "Working Directory",
        "应用权限授权" to "App Permission Authorization",
        "存储占用" to "Storage Usage",
        "清理" to "Clean",
        "重新分析" to "Reanalyze",
        "加载失败" to "Failed to load",
        "场景映射" to "Scene Mapping",
        "已安装模型" to "Installed Models",
        "自启动任务" to "Boot Tasks",
        "暂无" to "None",
        "暂无记忆" to "No memories",
        "暂无可配置场景" to "No configurable scenes",
        "暂无已接入的技能" to "No skills available",
        "暂无归档对话" to "No archived conversations",
        "暂无聊天记录" to "No conversations yet",
        "未命名对话" to "Untitled conversation",
        "折叠全部日期" to "Collapse all dates",
        "展开全部日期" to "Expand all dates",
        "还没有短期记忆" to "No short-term memory yet",
        "确定删除吗？" to "Are you sure you want to delete?",
        "删除后该内容将不可找回" to "This action cannot be undone",
        "立即整理一次" to "Rollup now",
        "夜间记忆整理（22:00）" to "Nightly Memory Rollup (22:00)",
        "最近执行" to "Last executed",
        "暂无总结内容" to "No summary content",
        "检查更新失败" to "Failed to check for updates",
        "已是最新版" to "Already up to date",
        "检查 GitHub Release 获取最新版本" to "Checking GitHub Release for the latest version",
        "检查中..." to "Checking...",
        "查看新版本" to "View new version",
        "检查更新" to "Check for updates",
        "已关闭思考" to "Thinking disabled",
        "请求日志" to "Request logs",
        "运行日志" to "Runtime logs",
        "使用手册" to "User guide",
        "概览" to "Overview",
        "最近记录" to "Recent logs",
        "最近 10 条 AI 请求，按时间倒序展示。" to "The latest 10 AI requests are shown in reverse chronological order.",
        "点击条目展开查看请求与响应正文。" to "Tap an entry to expand the request and response payloads.",
        "最近 200 条错误和崩溃日志，按时间倒序展示。" to "The latest 200 error and crash logs are shown in reverse chronological order.",
        "含堆栈的条目可展开查看。" to "Entries with stack traces can be expanded for details.",
        "导出运行日志" to "Export runtime logs",
        "已复制全部运行日志" to "All runtime logs copied",
        "导出运行日志失败" to "Failed to export runtime logs",
        "崩溃" to "Crash",
        "总数" to "Total",
        "最近一条" to "Latest entry",
        "基础信息" to "Basic info",
        "载荷" to "Payloads",
        "保存中..." to "Saving...",
        "未选择文件" to "No file selected",
        "远程地址" to "Remote URL",
        "后台运行权限" to "Background run permission",
        "应用列表读取" to "Installed apps access",
        "已开启" to "Enabled",
        "去开启" to "Enable",
        "清除缓存" to "Clear cache",
        "查看并配置悬浮窗、后台运行、Shizuku 等权限" to "Review overlay, background operation, Shizuku, and related permissions",
        "权限检查中..." to "Checking permissions...",
        "继续任务" to "Continue task",
        "继续任务仅要求" to "Continue requires only",
        "Termux 终端能力" to "Termux terminal capability",
        "可选，允许 Agent 通过 Termux 执行终端命令" to "Optional: allow the Agent to run terminal commands via Termux",
        "可选" to "Optional",
        "让小万带你执行一次任务吧！" to "Let Omnibot walk you through one task!",
        "其中 Termux 终端能力为可选项，未开启也不影响基础功能" to "Termux capability is optional; leaving it off will not affect basic features",
        "未绑定" to "Unbound",
        "恢复默认" to "Restore default",
        "点击右侧按钮后，可按 Provider 搜索、折叠并选择模型。" to "After tapping the button on the right, you can search, collapse, and select models by Provider.",
        "使用内置模型服务" to "Use Built-in Model Service",
        "内置模型服务" to "Built-in Model Service",
        "内置模型服务已启用" to "Built-in model service enabled",
        "自定义模型已启用" to "Custom model enabled",
        "已启用内置模型服务" to "Built-in model service enabled",
        "已切换为自定义模型" to "Switched to custom model",
        "没有匹配的模型" to "No matching models",
        "搜索模型 ID" to "Search model ID",
        "请先在模型提供商页配置 Provider" to "Please configure a provider in Model Providers first",
        "该 Provider 暂无可选模型" to "No selectable models for this provider",
        "请先配置ai服务商和模型" to "Please configure an AI provider and model first",
        "已进入仅聊天模式" to "Entered chat-only mode",
        "已退出仅聊天模式" to "Exited chat-only mode",
        "搜索技能名称或描述" to "Search skill name or description",
        "未找到匹配的技能" to "No matching skills found",
        "流式" to "Streaming",
        "非流式" to "Non-streaming",
        "请求地址" to "Request URL",
        "请求方法" to "Request Method",
        "错误信息" to "Error",
        "请求 JSON" to "Request JSON",
        "响应 JSON" to "Response JSON",
        "重试" to "Retry",
        "加载请求日志失败" to "Failed to load request logs",
        "最近还没有 AI 请求日志" to "No AI request logs yet",
        "加载运行日志失败" to "Failed to load runtime logs",
        "暂无运行日志" to "No runtime logs yet",
        "清除" to "Clear",
        "AI 请求" to "AI Request",
        "次对话" to "conversations",
        "天连续" to "day streak",
        "无对话" to "No conversations",
        "暂无 Token 消耗数据" to "No token usage data yet",
        "本地" to "Local",
        "云端" to "Cloud",
        "无消耗" to "No usage",
        "长期记忆未就绪" to "Long-term memory is not ready",
        "完成记忆初始化后，这里会展示跨会话沉淀的偏好与事实。" to "After memory initialization, cross-session preferences and facts will appear here.",
        "长期记忆暂时不可用" to "Long-term memory is temporarily unavailable",
        "长期记忆还是空的" to "Long-term memory is still empty",
        "当 Agent 主动写入长期偏好后，这里会逐渐丰富起来。" to "After the Agent writes long-term preferences, this section will gradually fill up.",
        "新增长期记忆" to "Add long-term memory",
        "刷新长期记忆" to "Refresh long-term memory",
        "刚刚" to "Just now",
        "思考完成" to "Thinking complete",
        "正在思考" to "Thinking",
        "用时" to "Elapsed",
        "准备执行任务..." to "Preparing to execute task...",
        "取消任务" to "Cancel task",
        "任务已取消" to "Task canceled",
        "停止工具" to "Stop tool",
        "正在停止工具" to "Stopping tool",
        "停止工具调用失败，请稍后重试" to "Failed to stop tool call. Please try again later.",
        "工具调用" to "Tool call",
        "超时" to "Timeout",
        "中断" to "Interrupted",
        "成功" to "Success",
        "失败" to "Failed",
        "运行中" to "Running",
        "浏览中" to "Browsing",
        "响应中" to "Responding",
        "处理中" to "Processing",
        "终端" to "Terminal",
        "浏览器" to "Browser",
        "定时" to "Scheduled",
        "提醒" to "Reminder",
        "日历" to "Calendar",
        "子任务" to "Subtask",
        "工具" to "Tool",
        "[更早记录已省略]" to "[Earlier records omitted]",
        "等待龙虾烹饪" to "Waiting for OpenClaw processing",
        "配置你的 AI 助手" to "Configure Your AI Assistant",
        "选择一种方式开始使用小万" to "Choose a way to start using the assistant",
        "云 AI 服务" to "Cloud AI Service",
        "连接 OpenAI、Anthropic 或兼容的 API 服务" to "Connect to OpenAI, Anthropic, or compatible APIs",
        "继续" to "Continue",
        "跳过，稍后在设置中配置" to "Skip, configure later in Settings",
        "云 AI 服务配置" to "Cloud AI Setup",
        "配置云端 AI 服务商，使用更强大的模型能力" to "Configure a cloud AI provider for more powerful models",
        "协议类型" to "Protocol Type",
        "名称" to "Name",
        "例如：我的 OpenAI" to "e.g., My OpenAI",
        "测试连接" to "Test Connection",
        "连接成功" to "Connected",
        "发现" to "found",
        "个模型" to "models",
        "连接失败" to "Connection failed",
        "保存" to "Save",
        "保存失败" to "Save failed",
        "下一步" to "Next",
        "暂停" to "Pause",
        "继续下载" to "Resume",
        "下载完成" to "Download Complete",
        "完成" to "Done",
        "返回" to "Back",
        "开始体验" to "Get Started",
        "API Key（可选）" to "API Key (optional)",
        "推荐" to "Recommended",
        "选择方式" to "Choose Method",
        "特性" to "Features",
        "初次使用教程" to "First-use Tutorial",
        "重新查看应用首次启动时的引导页面" to "Replay the first-launch onboarding page",
    )
}
